# Generated by Django 4.2 on 2023-04-12 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('contributor', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=250)),
                ('uploadedOn', models.DateTimeField(default=datetime.datetime(2023, 4, 12, 19, 47, 7, 317095))),
            ],
        ),
    ]
