# Generated by Django 4.2 on 2023-04-13 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_alter_podcastdetails_uploadedon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastdetails',
            name='url',
        ),
        migrations.AddField(
            model_name='podcastdetails',
            name='audio',
            field=models.FileField(default='null', upload_to='audio/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcastdetails',
            name='coverImage',
            field=models.FileField(default='null', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='podcastdetails',
            name='uploadedOn',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 21, 4, 25, 568157)),
        ),
    ]
