# Generated by Django 4.2 on 2023-04-14 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_remove_podcastdetails_url_podcastdetails_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastdetails',
            name='audio',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='podcastdetails',
            name='coverImage',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='podcastdetails',
            name='uploadedOn',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 8, 26, 53, 388301)),
        ),
    ]
