# Generated by Django 4.2 on 2023-04-14 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_alter_podcastdetails_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastdetails',
            name='uploadedOn',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 9, 10, 6, 195719)),
        ),
    ]
