# Generated by Django 4.2 on 2023-04-14 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0005_alter_podcastdetails_uploadedon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastdetails',
            name='uploadedOn',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 16, 46, 26, 999461)),
        ),
    ]
